# Generated by Django 4.0 on 2022-08-28 21:24

import core.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=10, validators=[core.users.validators.vcedula], verbose_name='Cédula o RUC'),
        ),
    ]
